description: "Restores air-images of person in a forest using Dinov2 Encoder and DPT Decoder"

# Training parameters
batch_size: 32
grad_accum_steps: 1
n_epochs: 150
max_grad_norm: 0.0
learning_rate: 0.00005

# Miscellaneous
num_workers: 0
checkpoint: null  # null in YAML represents None in Python
test: false       # false in YAML represents False in Python
pin_memory: false
precision: "32"

device:
  type: "cuda" # "cuda", "cpu"; null means auto-select cuda if available, else cpu
  ids: [0, 1, 2, 3] # [0], [0,1,2,3], [1,2,3]; null means auto-select all available GPUs

data:
  limit: null # sys.maxsize = 9223372036854775807
  oversample: true

datamodule: "DPTImageDataModule" # "EmbeddingDataModule", "ImageDataModule", "HFImageDataModule"

model: "DPT" # "UNet", "ModifiedConvHead", ("DPT")
backbone_size: "small"  # small, base, large
residual: True # if to learn the residual and not the gt
freeze_encoder: True # freezes all non-embedding layers of the encoder
out_features: [3, 6, 9, 12]

loss:
  use_msge: true
  msge_weight: 1.0

early_stopping:
  patience: 50
  min_delta: 0

img_standardization:
  do_standardize: false  # not used here.
  do_destandardize: false

wandb:
  project: "CV2023-share"
  entity: "cv2023-a6"
  group: "DINO DPT"
  notes: "Testing DINO with DPT"
  experiment_name: "Small 5e-5 MSGE 2.0"
