description: "Restores air-images of person in a forest using pre-computed DinoV2 Embeddings"

# Training parameters
batch_size: 200
grad_accum_steps: 1
n_epochs: 150
max_grad_norm: 0.0
learning_rate: 0.001

# Miscellaneous
num_workers: 0
checkpoint: null  # null in YAML represents None in Python
test: false       # false in YAML represents False in Python
pin_memory: false

device:
  type: "cuda" # "cuda", "cpu"; null means auto-select cuda if available, else cpu
  ids: [0,1,2,3] # [0], [0,1,2,3], [1,2,3]; null means auto-select all available GPUs

data:
  limit: null # sys.maxsize = 9223372036854775807
  oversample: false

loss:
  use_msge: true 
  msge_weight: 2.0

datamodule: "EmbeddingDataModule" # "EmbeddingDataModule", "ImageDataModule", "DPTImageDataModule"
model: "ModifiedConvHead" # "UNet", "ModifiedConvHead", ("DPT")
backbone_size: "small"  # small, base, large


early_stopping:
  patience: 50
  min_delta: 0

logging: True
wandb:
  project: "CV2023-share"
  entity: "cv2023-a6"
  group: "DINO ModifiedConvHead"
  notes: "Testing DINO with ModifiedConvHead"
  experiment_name: "Small 1e-3 MSGE 2.0"
