description: "Restores air-images of person in a forest using pre-computed DinoV2 Embeddings"

# Training parameters
batch_size: 120
grad_accum_steps: 1
n_epochs: 150
max_grad_norm: 0.0
learning_rate: 0.001

# Miscellaneous
num_workers: 0
checkpoint: null  # null in YAML represents None in Python
test: false       # false in YAML represents False in Python
pin_memory: false # false in YAML represents False in Python


datamodule: "EmbeddingDataModule" # "EmbeddingDataModule", "ImageDataModule", "HFImageDataModule"
model: "ModifiedConvHead" # "UNet", "ModifiedConvHead", ("DPT")
backbone_size: "small"  # small, base, large
# 
early_stopping:
  patience: 5
  min_delta: 0.001

wandb:
  project: "CV2023-share"
  group: "DINO ModifiedConvHead"
  notes: "Testing DINO with ModifiedConvHead"
  experiment_name: "DINO ModifiedConvHead"
