description: "Restores air-images of person in a forest using a simple UNet baseline"

# Training parameters
batch_size: 6
grad_accum_steps: 1
n_epochs: 150
max_grad_norm: 0.0
learning_rate: 0.001

# Miscellaneous
num_workers: 0
checkpoint: null  # null in YAML represents None in Python
test: false       # false in YAML represents False in Python
pin_memory: false # false in YAML represents False in Python


datamodule: "ImageDataModule" # "EmbeddingDataModule", "ImageDataModule", "HFImageDataModule"
model: "UNet" # "UNet", "ModifiedConvHead", ("DPT")

early_stopping:
  patience: 10
  min_delta: 0


# UNet
img_standardization:
  do_standardize: true
  do_destandardize: false
  mean: 109.1209
  std: 18.0851


# HFImageDataModule
# just an example, not actually used here.
backbone_model_name: "facebook/dpt-dinov2-small-nyu"

wandb:
  project: "CV2023-share"
  group: "UNet"
  notes: "Testing UNet baselines!"
  experiment_name: "UNet standardization"